# Generated by Django 3.2.5 on 2021-07-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_auto_20210729_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-id']},
        ),
    ]
